/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/superadmin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginSuperadmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/active-organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setActiveOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setChannelDisabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setChannelCustomer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/posting-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setChannelPostingTimes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/telegram/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openTelegramConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/telegram/connections/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTelegramConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{provider}/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts connecting (or, with channelId, reconnecting) a channel with OAuth. The screen sends the browser to url. */
        post: operations["startChannelAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The pages the member who connected a channel in between steps can choose from. */
        get: operations["listChannelPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Chooses the page of a channel in between steps. Answers the channel that holds the page, which is another one when the page was already connected. */
        put: operations["chooseChannelPage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMedia"];
        put?: never;
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMedia"];
        post?: never;
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTags"];
        put?: never;
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateTag"];
        post?: never;
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCalendarPosts"];
        put?: never;
        post: operations["createPosts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/next-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["nextSlot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPost"];
        put: operations["updatePost"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["movePost"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["linkPostRelease"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePostGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setEmailPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["readNotifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
        };
        TagInput: {
            name: string;
            color: string;
        };
        PostMediaRef: {
            /** Format: uuid */
            id: string;
        };
        PostValueInput: {
            content: string;
            delayMinutes: number;
            media: components["schemas"]["PostMediaRef"][];
        };
        PostMedia: {
            /** Format: uuid */
            id: string;
            url: string;
            kind: string;
            alt?: string;
            thumbnailUrl?: string;
            thumbnailSeconds?: number;
        };
        PostValue: {
            content: string;
            delayMinutes: number;
            media: components["schemas"]["PostMedia"][];
        };
        ChannelPostInput: {
            /** Format: uuid */
            channelId: string;
            values: components["schemas"]["PostValueInput"][];
            settings: {
                [key: string]: unknown;
            };
        };
        NewPosts: {
            /** @enum {string} */
            type: "schedule" | "draft" | "now";
            /** Format: date-time */
            publishAt: string;
            tags: string[];
            posts: components["schemas"]["ChannelPostInput"][];
        };
        CreatedGroup: {
            /** Format: uuid */
            groupId: string;
            posts: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                channelId: string;
            }[];
        };
        Problem: {
            code: string;
            /** Format: uuid */
            channelId?: string;
            valueIndex?: number;
        };
        InvalidPost: {
            code: string;
            message: string;
            problems: components["schemas"]["Problem"][];
        };
        PostChannel: {
            /** Format: uuid */
            id: string;
            name: string;
            provider: string;
            picture?: string;
            /** Format: uuid */
            customerId?: string;
        };
        CalendarPost: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            groupId: string;
            /** @enum {string} */
            status: "draft" | "scheduled" | "published" | "error";
            /** Format: date-time */
            publishAt: string;
            excerpt: string;
            channel: components["schemas"]["PostChannel"];
            tags: components["schemas"]["Tag"][];
            releaseUrl?: string;
            error?: string;
        };
        PostPage: {
            items: components["schemas"]["CalendarPost"][];
            page: number;
            pages: number;
            total: number;
        };
        PostDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            groupId: string;
            /** @enum {string} */
            status: "draft" | "scheduled" | "published" | "error";
            /** Format: date-time */
            publishAt: string;
            channel: components["schemas"]["PostChannel"];
            values: components["schemas"]["PostValue"][];
            settings: {
                [key: string]: unknown;
            };
            tags: components["schemas"]["Tag"][];
            releaseUrl?: string;
            error?: string;
        };
        PostEdit: {
            /** @enum {string} */
            mode: "update" | "schedule";
            republish?: boolean;
            /** Format: date-time */
            publishAt: string;
            values: components["schemas"]["PostValueInput"][];
            settings: {
                [key: string]: unknown;
            };
            tags: string[];
        };
        PostMove: {
            /** Format: date-time */
            publishAt: string;
            /** @enum {string} */
            mode: "update" | "schedule";
            republish?: boolean;
        };
        Media: {
            /** Format: uuid */
            id: string;
            name: string;
            url: string;
            /** @enum {string} */
            kind: "image" | "video";
            mime: string;
            /** Format: int64 */
            size: number;
            alt: string;
            thumbnailUrl?: string;
            thumbnailSeconds?: number;
            /** Format: date-time */
            createdAt: string;
        };
        MediaPage: {
            items: components["schemas"]["Media"][];
            page: number;
            pages: number;
            total: number;
        };
        MediaUpdate: {
            alt?: string;
            /** Format: uuid */
            thumbnailMediaId?: string | null;
            thumbnailSeconds?: number | null;
        };
        Provider: {
            identifier: string;
            name: string;
        };
        Customer: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Channel: {
            /** Format: uuid */
            id: string;
            provider: string;
            name: string;
            username: string;
            picture?: string;
            disabled: boolean;
            refreshNeeded: boolean;
            inBetweenSteps: boolean;
            customer?: components["schemas"]["Customer"];
            postingTimes: number[];
        };
        ChannelAuthorizationInput: {
            /**
             * Format: uuid
             * @description The channel to reconnect.
             */
            channelId?: string;
        };
        ChannelAuthorization: {
            url: string;
        };
        ChannelPage: {
            id: string;
            name: string;
            picture?: string;
        };
        /** @description With name, moves by name (created if missing; blank removes). Otherwise moves to customerId, or removes when it is absent or null. */
        ChannelCustomer: {
            name?: string;
            /** Format: uuid */
            customerId?: string | null;
        };
        TelegramConnection: {
            code: string;
            botUsername: string;
        };
        TelegramConnectionStatus: {
            /** @enum {string} */
            status: "pending" | "connected" | "expired";
            /** Format: uuid */
            channelId?: string;
        };
        Instance: {
            superadminTotp: boolean;
            languages: string[];
            oidc?: components["schemas"]["OidcProvider"];
        };
        OidcProvider: {
            name: string;
        };
        ActiveOrganization: {
            /** Format: uuid */
            organizationId: string;
        };
        SuperadminLogin: {
            username: string;
            password: string;
            code?: string;
        };
        Me: {
            /** @enum {string} */
            kind: "superadmin" | "member";
            user?: components["schemas"]["MeUser"];
            organizations?: components["schemas"]["MeOrganization"][];
            /** Format: uuid */
            activeOrganizationId?: string;
        };
        MeUser: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            emailSuccess: boolean;
            emailFailure: boolean;
        };
        EmailPreferences: {
            emailSuccess: boolean;
            emailFailure: boolean;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "info" | "failure" | "success";
            template: string;
            params: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            unread: boolean;
        };
        NotificationList: {
            items: components["schemas"]["Notification"][];
            unread: number;
        };
        MeOrganization: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            role: "USER" | "ADMIN" | "OWNER";
        };
    };
    responses: {
        /** @description The post does not pass validation */
        InvalidPost: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InvalidPost"];
            };
        };
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TagID: string;
        PostID: string;
        MediaID: string;
        ChannelID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public instance configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
        };
    };
    loginSuperadmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuperadminLogin"];
            };
        };
        responses: {
            /** @description Session opened */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session closed */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setActiveOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveOrganization"];
            };
        };
        responses: {
            /** @description Active organization changed */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers with credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channels of the active organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setChannelDisabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setChannelCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCustomer"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setChannelPostingTimes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    times: number[];
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customers of the active organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    openTelegramConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending connection */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramConnection"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    getTelegramConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramConnectionStatus"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    startChannelAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelAuthorizationInput"];
            };
        };
        responses: {
            /** @description Authorization started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelAuthorization"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listChannelPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPage"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    chooseChannelPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pageId: string;
                };
            };
        };
        responses: {
            /** @description The channel of the page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    listMedia: {
        parameters: {
            query?: {
                page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    updateMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags of the active organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TagID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TagID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listCalendarPosts: {
        parameters: {
            query: {
                from: string;
                to: string;
                customer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Posts of the range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarPost"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPosts"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedGroup"];
                };
            };
            400: components["responses"]["InvalidPost"];
            401: components["responses"]["Error"];
        };
    };
    listPosts: {
        parameters: {
            query?: {
                page?: number;
                status?: "all" | "scheduled" | "draft" | "published";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of posts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    nextSlot: {
        parameters: {
            query?: {
                channelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next free slot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        date: string;
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostEdit"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            400: components["responses"]["InvalidPost"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    movePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostMove"];
            };
        };
        responses: {
            /** @description Moved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    linkPostRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    url: string;
                };
            };
        };
        responses: {
            /** @description Linked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deletePostGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setEmailPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailPreferences"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest notifications of the active organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    readNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
}
